# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.3.0
FROM ruby:$RUBY_VERSION-slim

WORKDIR /app

# Install base dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    libpq-dev \
    libvips \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy app code (overridden later by volume)
COPY . .

# Use Rails server by default
CMD ["bash", "-c", "bundle exec rails server -b 0.0.0.0"]
